kind: OperatorGroup
apiVersion: operators.coreos.com/v1
metadata:
  name: og-single
  namespace: external-secrets
spec:
  targetNamespaces:
  - external-secrets
---
piVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-external-secrets-operator
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  channel: alpha
  name: external-secrets-operator
  source: operatorhubio-catalog
  sourceNamespace: olm