apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    name: ''
    namespace: '*'
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/operators/external-secrets/overlays/default
    repoURL: 'https://github.com/cnuland/k8s-hello-chris-ai.git'
    targetRevision: HEAD
    directory:
      recurse: false
  sources: []
  project: default
  syncOptions:
    - CreateNamespace=true
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
    automated:
      prune: true
      selfHeal: true