apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: operators
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: ''
    namespace: '*'
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/operators/keda/overlays/default
    repoURL: 'https://github.com/cnuland/k8s-hello-chris-ai.git'
    targetRevision: HEAD
    directory:
      recurse: false
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
