apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-bus-trigger
  namespace: operators
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  ignoreDifferences:
  - group: "*"
    kind: "ScaledJob"
    jsonPointers:
    - /metadata/labels
  - group: "*"
    kind: "TriggerAuthentication"
    jsonPointers:
    - /metadata/labels
  destination:
    name: ''
    namespace: '*'
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/hello-chris/keda
    repoURL: 'https://github.com/cnuland/k8s-hello-chris-ai.git'
    targetRevision: HEAD
    directory:
      recurse: false
  sources: []
  project: default
  syncPolicy:
  syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: operators
    automated:
      prune: true
      selfHeal: true