apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weaviate
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"

spec:
  destination:
    name: ''
    namespace: 'weaviate'
    server: 'https://kubernetes.default.svc'
  source:
    chart: weaviate
    repoURL: https://weaviate.github.io/weaviate-helm
    targetRevision: 16.7.0
    helm:
      releaseName: weaviate
      parameters:
      - name: "modules.text2vec-openai.enabled"
        value: "true"
  sources: []
  project: default
  syncOptions:
    - CreateNamespace=true
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: argocd
    automated:
      prune: true
      selfHeal: true