apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: god-mode
rules:
- apiGroups: [""] #specifies core api groups
  resources: ["*"]
  verbs: ["*"]