apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace/openshift-keda-operator.yaml
- namespace/external-secrets.yaml
- namespace/weaviate.yaml
- operator/argocd-gitops-operator.yaml
- gitops/app-of-apps.yaml

