apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: 'argocd'
    server: 'https://kubernetes.default.svc'
  source:
    path: k8s/apps
    repoURL: 'https://github.com/cnuland/k8s-hello-chris-ai.git'
    targetRevision: HEAD
    directory:
      recurse: false
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true