apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: clone-build-push
spec:
  pipelineRef:
    name: clone-build-push
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    persistentvolumeclaim:
      claimName: tekton-pvc
  - name: docker-credentials
    secret:
      secretName: docker-credentials
  params:
  - name: repo-url
    value: "https://github.com/cnuland/k8s-hello-chris-ai.git"
  - name: image-reference
    value: "quay.io/cnuland/azure-pop-queue:latest"
  - name: docker-path
    value: "./Dockerfile"
  - name: context
    value: "./"
  - name: git-revision
    value: "main"