apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: file-system-access-binding
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: hello-chris
roleRef:
  kind: ClusterRole
  name: cluster-admin # This is me being lazy. Demo clusters only. NOT FOR PRODUCTION USE
  apiGroup: rbac.authorization.k8s.io