apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- infra/pipelines.yaml
- infra/external-secrets.yaml
- app/hello-chris.yaml
- infra/onboarding.yaml
- infra/triggers.yaml
- operators.yaml